 version: "3.7"

 services:
   tests:
     image: mcr.microsoft.com/dotnet/sdk:6.0
     command: dotnet test
     working_dir: /src/Onwrd.EntityFrameworkCore.Tests
     volumes:
       - ../:/src
     depends_on:
       - db
     environment:
        DATABASE_SERVER: db
        DATABASE_USER: sa
        DATABASE_PASSWORD: "Qx#)T@pzKgAV^+tw"
   db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Qx#)T@pzKgAV^+tw"
        ACCEPT_EULA: "Y"