name: CI

on:

  push:
    branches:
      - main

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run docker compose (with NUKE build)
        working-directory: ./pipelines
        run: docker compose up  --abort-on-container-exit
        env:
          ONWRD_VERSION: "0.1" # Doesn't matter for CI builds because no packages get pushed  
          ONWRD_NUGETAPIKEY: ${{ secrets.ONWRD_NUGETAPIKEY }}
          ONWRD_PUSHPACKAGE: false
