name: CI

on:

  push:
    branches:
      - main

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run NUKE build
        working-directory: ./pipelines/build
        run: dotnet run

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/ # or path/to/artifact
