# Downloads the latest CI artifact (from main) and pushes to NuGet
name: Release

on:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run NUKE build
        working-directory: ./pipelines/build/build
        run: dotnet run
        env:
          ARTIFACT_DIRECTORY: "./artifacts"
      
      - name: Evaluate build version
        run: echo "VERSION=0.5.${{ github.run_number }}-beta" >> $GITHUB_ENV

      - name: Run NUKE release (Push to NuGet)
        working-directory: ./pipelines/deploy/build
        run: dotnet run
        env:
          NuGetApiKey: ${{ secrets.ONWRD_NUGETAPIKEY }}
          ArtifactDirectory: "./artifacts"
          Version: ${{ github.VERSION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: onwrd
          path: "./artifacts"